grasp_service:
  ros__parameters:
    joints_names:
      - joint_1
      - joint_2
      - joint3

    positions_to_target_list:
      - FirstPostion
      - SecondPostion

    positions_to_target:
      FirstPostion: [0.1, 0.2, 0.3]
      SecondPostion: [0.1, 0.2, 0.3]

    times_for_postions_to_target:
      FirstPostion: 3
      SecondPostion: 4

    positions_to_home_list:
      - FirstPostion
      - SecondPostion

    positions_to_home:
      FirstPostion: [-0.1, -0.2, -0.3]
      SecondPostion: [-0.1, -0.2, -0.3]

    times_for_postions_to_home:
      FirstPostion: 12
      SecondPostion: 6

    time_to_wait_on_target: 5