grasp_service:
  ros__parameters:
    joints_names:
      - joint1
      - joint2
      - joint3
      - joint4

    positions_to_target_list:
      - first_pos
      - second_pos

    positions_to_target:
      first_pos: [0.50, 0.0, 0.0, 0.0]
      second_pos: [-0.50, 0.0, 0.0, 0.0]

    times_for_positions_to_target:
      first_pos: 2
      second_pos: 4

    positions_to_home_list:
      - first_pos

    positions_to_home:
      first_pos: [0.50, 0.0, 0.0, 0.0]

    times_for_positions_to_home:
      first_pos: 2

    time_to_wait_on_target: 5