grasp_service:
  ros__parameters:
    joints_controller_name: joint_trajectory_controller
    joints_names:
      - joint1
      - joint2
      - joint3
      - joint4

    positions_to_target_list:
      - first_pos
      - second_pos

    positions_to_target:
      first_pos:
        positions: [0.50, 0.0, 0.0, 0.0]
        time_to_target: 2
      second_pos:
        positions: [-0.50, 0.0, 0.0, 0.0]
        time_to_target: 2

    positions_to_home_list:
      - first_pos

    positions_to_home:
      first_pos:
        positions: [0.50, 0.0, 0.0, 0.0]
        time_to_target: 2

    time_to_wait_on_target: 5

    gripper_controller_name: gripper_action_controller
    gripper_close: -0.01
    gripper_open: 0.019
