---
name: Build and Test (rolling)

on:
    push:
        branches: [rolling]

    pull_request:
        branches: [rolling]

    workflow_dispatch:
    schedule:
        - cron: '15 14 * * 6'

jobs:
    build:
        runs-on: ubuntu-latest
        container:
            image: ubuntu:noble

        steps:
            - uses: ros-tooling/setup-ros@v0.7
              with:
                  use-ros2-testing: true
            - uses: ros-tooling/action-ros-ci@v0.3
              with:
                  target-ros2-distro: rolling
