---
name: ROS

on:
    pull_request:
    push:
        branches:
            - foxy*
            - humble*
            - iron*
            - rolling*
            - main*
    workflow_dispatch:

jobs:
    lint:
        name: ament_${{ matrix.linter }}
        runs-on: ubuntu-latest
        container:
            image: ubuntu:jammy
        strategy:
            fail-fast: false
            matrix:
                linter: [xmllint, flake8, pep257]
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Run linter
              uses: ./.github/actions/lint/
              env:
                  LINTER: ${{ matrix.linter }}
